name: DevSkim

on:
  workflow_dispatch:

jobs:
  DevSkim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/DevSkim-Action@v1
        with:
          # The sub directory of the repository root to scan. Repository root used by default.
          directory-to-scan: $GITHUB_WORKSPACE
          # Optionally scan the contents of archives.
          should-scan-archives: true
          # The filename for the output.
          output-filename: devskim-results.sarif
          # The sub directory for the output under GITHUB_WORKSPACE.
          output-directory: $GITHUB_WORKSPACE

      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif
