# This is a basic workflow to help you get started with Actions

name: DevSkim

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: microsoft/DevSkim-Action@v1
        with:
          # The sub directory of the repository root to scan. Repository root used by default.
          directory-to-scan: $GITHUB_WORKSPACE
          # Optionally scan the contents of archives.
          should-scan-archives: true
          # The filename for the output.
          output-filename: devskim-results.sarif
          # The sub directory for the output under GITHUB_WORKSPACE.
          output-directory: $GITHUB_WORKSPACE

      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif
